---
- name: Install Dokku
  sudo: yes
  hosts: dokku
  vars:
    public_key: '~/.ssh/id_rsa.pub'
    swap_file_path: /swapfile
    swap_sector_count: 2048k
    dokku_plugins:
      - https://github.com/dokku/dokku-postgres.git
      - https://github.com/dokku/dokku-mariadb.git
    backup_dir: /home/dokku/backup
    backup_s3_bucket: 'backup_bucket_name'
    backup_alert_command: "curl -fsS --retry 3 https://hchk.io/3d82de35-bce7-449d-8d54-274eae59d7f2 > /dev/null"
    databases:
      - {engine: 'postgres', name: 'appdb'}
      - {engine: 'mariadb', name: 'mydb'}

  pre_tasks: []

  roles:
    - { role: swap, when: ansible_ssh_user != "vagrant" }
    - dokku
    - { role: backup, when: ansible_ssh_user != "vagrant" }

  post_tasks:

    - name: Add Public Key into main user
      authorized_key: user={{ ansible_ssh_user }} key="{{ lookup('file', public_key) }}"

    - name: Add Public Key into Dokku user
      shell: echo "{{ lookup('file', public_key) }}" | sshcommand acl-add dokku deployment_key
