---
- name: Update SSL, Python and NTP
  apt: name={{ item }} update_cache=yes state=latest 
  with_items:
    - ca-certificates
    - openssl
    - python
    - ntp

- name: Add packagecloud.io key into apt
  apt_key: url={{ item }} state=present
  with_items:
    - https://packagecloud.io/gpg.key

- name: Add Dokku Key
  apt_key: url={{ item }}
  with_items:
    - 'https://apt.dockerproject.org/gpg'
    - 'https://packagecloud.io/gpg.key'

- name: Add Docker and Dokku repos into source list
  apt_repository: repo={{ item }} state=present
  with_items:
    - 'deb https://apt.dockerproject.org/repo ubuntu-trusty main'
    - 'deb https://packagecloud.io/dokku/dokku/ubuntu/ trusty main'

- name: Install Dokku and necessary soft like Docker with apt
  apt: pkg={{ item }} state=latest update_cache=yes
  with_items: 
    - git
    - daemontools
    - build-essential
    - libtool
    - docker
    - dokku

- name: Add user into Docker group
  user: name={{ansible_user_id}} groups=docker append=yes

- name: Dokku postinstall
  shell: dokku plugin:install-dependencies --core

- name: Install dokku plugins
  shell: dokku plugin:install {{ item }} --name {{ item.split('/')[-1].split('-')[-1] }}
  with_items: dokku_plugins
